CREATE DATABASE Primeiro;

CREATE TABLE Direção (
COD_DIRECAO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SENHA VARCHAR(8) NOT NULL
);

CREATE TABLE Funcionarios (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
COD_DEPARTAMENTO VARCHAR(5) NOT NULL,
 SENHA VARCHAR(8) NOT NULL,
 FUNCAO VARCHAR(20) NOT NULL
 );